- id: letsencrypt-renewal
  alias: "Let's Encrypt Renewal"
  trigger:
  - platform: time
    at: '00:00:00'
  action:
  - service: hassio.addon_restart
    data:
      addon: core_letsencrypt

- id: room-temperature-change
  alias: "Change in room temperature"
  trigger:
    platform: state
    entity_id: sensor.livingroom_temperature
  condition:
  - condition: template
    value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
  action:
  - service: notify.notify_html5
    data_template:
      title: "Room temperature"
      message: "Current temperature: {{ states.sensor.livingroom_temperature.state }} C"
    data:
      data:
        tag: 'notification-room-temperature'

- id: kids-bedroom-switch-on-globe
  alias: "Lights+Globe on in bedroom kids"
  trigger:
    platform: state
    entity_id: switch.fb_kids_bedroom
    to: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.sw_globe

- id: kids-bedroom-switch-off-globe
  alias: "Globe off in bedroom kids"
  trigger:
    platform: state
    entity_id: switch.fb_kids_bedroom
    to: 'off'
    for:
      minutes: 10
  action:
  - service: switch.turn_off
    entity_id: switch.sw_globe

- id: dryer-ready
  alias: "Dryer is ready"
  trigger:
    platform: state
    entity_id: sensor.dryer_status
    to: 'off'
    for:
      minutes: 1
  action:
  - service: script.chime_announcement_broadcast
    data:
      message: 'De droger is klaar.'
  - service: notify.notify_html5
    data_template:
      title: "Droger"
      message: "Op {{ now().day }}-{{ now().month }} om {{ now().hour }}:{{ now().minute }} was de droger klaar."
    data:
      data:
        tag: 'notification-dryer'

- id: washer-ready
  alias: "Washer is ready"
  trigger:
    platform: state
    entity_id: sensor.washer_status
    to: 'off'
    for:
      minutes: 1
  action:
  - service: script.chime_announcement_broadcast
    data:
      message: 'De wasmachine is klaar.'
  - service: notify.notify_html5
    data_template:
      title: "Wasmachine"
      message: "Op {{ now().day }}-{{ now().month }} om {{ now().hour }}:{{ now().minute }} was de wasmachine klaar."
    data:
      data:
        tag: 'notification-washer'
