input_number:
  alarm_1_hour:
    name: Hours
    icon: mdi:timer
    initial: 7
    min: 0
    max: 23
    step: 1
  alarm_1_minutes:
    name: Minutes
    icon: mdi:timer
    initial: 30
    min: 0
    max: 59
    step: 1

input_boolean:
  alarm_1_weekday:
    name: Weekdays
    initial: off
    icon: mdi:calendar
  alarm_1_weekend:
    name: Weekends
    initial: off
    icon: mdi:calendar

sensor:
  - platform: template
    sensors:
      alarm_1_time:
        friendly_name: 'Time'
        value_template: >-
          {{ "%0.02d:%0.02d" | format(states("input_number.alarm_1_hour") | int, states("input_number.alarm_1_minutes") | int) }}

group:
  alarm_1:
    name: Wake Me Up
    entities:
      - sensor.alarm_1_time
      - input_number.alarm_1_hour
      - input_number.alarm_1_minutes
      - input_boolean.alarm_1_weekday
      - input_boolean.alarm_1_weekend

automation:
  - id: alarm_1_weekdays
    alias: "Wake me up (week)"
    trigger:
      - platform: time_pattern
        minutes: '/1'
        seconds: 0
    condition:
      - condition: state
        entity_id: input_boolean.alarm_1_weekday
        state: 'on'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: template
        value_template: >-
          {{ now().strftime("%H:%M") == states.sensor.alarm_1_time.state }}
    action:
      #- event: alarm_1_event
      #  event_data:
      #    name: Alarm 1 Triggered
      #    type: Weekdays
      service: script.alarm_workday

  - id: alarm_1_weekend
    alias: "Wake me up (weekend)"
    trigger:
      - platform: time_pattern
        minutes: '/1'
        seconds: 0
    condition:
      - condition: state
        entity_id: input_boolean.alarm_1_weekend
        state: 'on'
      - condition: time
        weekday:
            - sat
            - sun
      - condition: template
        value_template: >-
          {{ now().strftime("%H:%M") == states.sensor.alarm_1_time.state }}
    action:
      #event: alarm_1_event
      #event_data:
      #  name: Alarm 1 Triggered
      #  type: Weekends
      service: script.alarm_weekend