homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 4 #meters above sealevel
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml
  packages:
    alarm: !include packages/alarm.yaml

frontend:
config:
ios:

http:
  api_password: !secret http_password
  #base_url: !secret base_url
  #ssl_certificate: /ssl/fullchain.pem
  #ssl_key: /ssl/privkey.pem

recorder:
  purge_keep_days: 365
  db_url: !secret recorder_db_url

updater:

discovery:
  ignore:
   - philips_hue
   - harmony

conversation:
history:
logbook:
map:
sun:
emulated_hue:
system_health:
person:

googlehome:
  devices:
    - host: 10.0.0.130
    - host: 10.0.0.131
    - host: 10.0.0.133
    - host: 10.0.0.135
    - host: 10.0.0.136

emulated_roku:
  servers:
    - name: Home Assistant
      listen_port: 8060
      host_ip: 10.0.0.40

notify:
  - platform: html5
    name: notify_html5
    gcm_api_key: !secret notify_apikey
    gcm_sender_id: !secret notify_senderid

binary_sensor:
  - platform: template
    sensors:
      people_home:
        friendly_name: "Anybody home"
        value_template: >-
          {{ is_state('group.karentracking', 'home')
             or is_state('group.pjtracking', 'home') }}


tts:
  - platform: google
    language: 'nl'

cloud:
  google_actions:
    filter:
      exclude_entities:
        - switch.outside

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 31
  platform: smart_life
  
group: !include_dir_merge_named groups/
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
light: !include lights.yaml
zone: !include zones.yaml
switch: !include switches.yaml
scene: !include scenes.yaml
input_boolean: !include input_booleans.yaml
shell_command: !include shell_commands.yaml
sensor: !include sensors.yaml

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret configurator_url

device_tracker:
  - platform: bluetooth_tracker
    new_device_defaults:
      track_new_devices: False
      hide_if_away: True
  - platform: google_maps
    username: !secret tracker_username
    password: !secret tracker_password
    max_gps_accuracy: 1000

asuswrt:
  host: 10.0.0.250
  username: !secret router_username
  password: !secret router_password
  sensors:
    - upload
    - download
    - upload_speed
    - download_speed

camera:
  - platform: generic
    name: Speelkamer
    still_image_url: http://10.0.0.50/image.jpg
    username: !secret camera_username
    password: !secret camera_password
  - platform: generic
    name: Slaapkamer
    still_image_url: http://10.0.0.55/image/jpeg.cgi        
    username: !secret camera_username
    password: !secret camera_password

input_select:
  camera_control_sleep:
    name: Camera Sleep
    options:
      - Home
      - Window
    initial: Home
    icon: mdi:camera-switch
  camera_control_play:
    name: Camera Play
    options:
      - Home
    initial: Home
    icon: mdi:camera-switch

media_player:
  - platform: kodi
    host: 10.0.0.100
    name: Kodi
    enable_websocket: false
  - platform: spotify
    client_id: !secret spotify_id
    client_secret: !secret spotify_secret
    aliases:
        7e4ca307628f40399bd6b7351af21693: 'Living Room'
        9ef9b510d8934a1cad077cd53f5d9922: 'Kitchen'
        6450335c726648a7ba710051a7f31f4d: 'Bedroom'
        7389151848bc4cb19c162e7165a05460: 'Bathroom'
        94d0fa8e056d4738bea4e43b2658f126: 'Kids'
        764b60d5d5944deeb2c2c930f84fc09a: 'Receiver'
    
zwave:
  usb_path: /dev/serial/by-id/usb-0658_0200-if00
  debug: true
  network_key: !secret zwave_network_key

remote:
  - platform: harmony
    name: Harmony
    host: 10.0.0.120
    activity: Source music

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

#logger:
#  default: warning
#  logs:
#    homeassistant.components.media_player.spotify: info