- id: letsencrypt-renewal
  alias: "Let's Encrypt Renewal"
  trigger:
  - platform: time
    at: '00:00:00'
  action:
  - service: hassio.addon_restart
    data:
      addon: core_letsencrypt

- id: room-temperature-change
  alias: "Change in room temperature"
  trigger:
    - platform: state
      entity_id: sensor.livingroom_temperature
    - platform: state
      entity_id: sensor.hottub_water_temperature
  condition:
  - condition: template
    value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
  action:
  - service: notify.notify_html5
    data_template:
      title: "Home Assistant"
      message: "Room temperature: {{ states.sensor.livingroom_temperature.state }} C\nWater temperature: {{ states.sensor.hottub_water_temperature.state }} C\nHottub is {{ states.sensor.hottub_state.state }}"
    data:
      data:
        tag: 'notification-room-temperature'

- id: kids-bedroom-switch-on-globe
  alias: "Lights+Globe on in bedroom kids"
  trigger:
    platform: state
    entity_id: switch.fb_kids_bedroom
    to: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.sw_globe

- id: kids-bedroom-switch-off-globe
  alias: "Globe off in bedroom kids"
  trigger:
    platform: state
    entity_id: switch.fb_kids_bedroom
    to: 'off'
    for:
      minutes: 10
  action:
  - service: switch.turn_off
    entity_id: switch.sw_globe

- id: kids-bedroom-switch-on-tree
  alias: "Lights+Tree on in bedroom kids"
  trigger:
    platform: state
    entity_id: switch.fb_kids_bedroom
    to: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.sw_kids_tree

- id: kids-bedroom-switch-off-tree
  alias: "Tree off in bedroom kids"
  trigger:
    platform: state
    entity_id: switch.fb_kids_bedroom
    to: 'off'
    for:
      minutes: 15
  action:
  - service: switch.turn_off
    entity_id: switch.sw_kids_tree

- id: livingroom-switch-on-sphere
  alias: "Sphere on in livingroom"
  trigger:
    platform: state
    entity_id: switch.fb_kitchen_top_right
    to: 'on'
  action:
  - service: light.turn_on
    entity_id: light.table

- id: livingroom-switch-off-sphere
  alias: "Sphere off in livingroom"
  trigger:
    platform: state
    entity_id: switch.fb_kitchen_top_right
    to: 'off'
  action:
  - service: light.turn_off
    entity_id: light.table

- id: dryer-ready
  alias: "Dryer is ready"
  trigger:
    platform: state
    entity_id: sensor.dryer_status
    to: 'off'
    for:
      minutes: 1
  action:
  - service: script.chime_announcement_broadcast
    data:
      message: 'De droger is klaar.'

- id: washer-ready
  alias: "Washer is ready"
  trigger:
    platform: state
    entity_id: sensor.washer_status
    to: 'off'
    for:
      minutes: 1
  action:
  - service: script.chime_announcement_broadcast
    data:
      message: 'De wasmachine is klaar.'
